### ISSUE TITLE
Support label fields

### ISSUE THREAD

**Issue by cfjedimaster** [Krutie/distraction-free-vue-form#1]
Please forgive the quick 'drive by' issue - I'd try a PR myself (and may later) but I saw this while doing the demo. Consider adding Label support to make working w/ radio/checkbox fields easier. I noticed the lack of it right away as it was easier to click the text then the checkbox/radio button.

**Comment by Krutie** [comment]
@cfjedimaster This has been resolved in this [commit](https://github.com/Krutie/distraction-free-vue-form/commit/ea27acb3413f41571bdd8d5615b5a8ed681c7890). 
And I have also updated the [demo](http://distraction-free-vue-form.surge.sh/) on Surge.

**Comment by cfjedimaster** [comment]
Perfect, thank you! (And awesome demo by the way!)
