### ISSUE TITLE
Migration to Vue 3

### ISSUE THREAD

**Issue by joypoddar** [Krutie/distraction-free-vue-form#14]
This project is a great learning resource. Unfortunately, I am starting off as a developer and am using Vue3. Will this project be migrated to Vue 3? It would really help if that was possible.

**Comment by Krutie** [comment]
Vue 3 version of this repo is in the pipeline. The idea is to use XState along with Vue 3 and TypeScript.

**Comment by Krutie** [comment]
> This project is a great learning resource. Unfortunately, I am starting off as a developer and am using Vue3. Will this project be migrated to Vue 3? It would really help if that was possible.

The Vue 3 version of this repo is in the pipeline. I'll update this repo once the new version is available.

**Comment by backurdi** [comment]
Hey Krutie, Really great repo, What are the expectations for migrating to Vue3?

**Comment by Krutie** [comment]
Hey @joypoddar & @backurdi 

Thanks for being patience.

I have just finished converting this project into Vue 3. 
You may want to check it out here: https://github.com/Krutie/advanced-vue3-form 

Please have a look at the readme file for more details. Other than that, I have tried to keep most of the structure as it is.
